import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Prepares a local development environment. It never creates a staff account:
 * access is granted by a role code redeemed through the claim flow, so there is no
 * seeded identity for anyone to guess. See docs/decisions/0002-access-and-verification.md.
 */
async function main() {
  const root = process.cwd();
  const envPath = resolve(root, ".env.local");
  const createdEnvironment = !existsSync(envPath);

  if (createdEnvironment) {
    writeFileSync(
      envPath,
      [
        "# Generated by pnpm setup. Development only.",
        "DATABASE_URL=data/pouch-villa-prototype.db",
        `AUTH_SECRET=${randomBytes(32).toString("base64url")}`,
        "NEXT_PUBLIC_SITE_URL=http://localhost:3000",
        "NEXT_PUBLIC_SITE_INDEXABLE=false",
        "",
      ].join("\n"),
      "utf8",
    );
    console.log("Created .env.local with a new development signing key.");
  } else {
    console.log("Existing .env.local preserved.");
  }

  mkdirSync(resolve(root, "data"), { recursive: true });
  const { loadEnvFiles } = await import("../src/env");
  loadEnvFiles(root);
  const { getDatabase } = await import("../src/db/index");
  const db = getDatabase();
  const count = db.prepare("SELECT COUNT(*) AS count FROM products").get() as { count: number };

  console.log(`Database ready with ${count.count} demonstration products.`);
  console.log("No staff account exists. Mint a role code to claim one.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
