import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Prepares a local development environment.
 *
 * It creates no staff account and no catalogue data. Access is granted by
 * redeeming a role code, so there is no seeded identity for anyone to guess, and
 * an empty catalogue is shown honestly rather than filled with invented products.
 *
 * Run `pnpm --filter @pv/backend db:migrate` afterwards to build the schema.
 */
function main() {
  const root = resolve(process.cwd(), "../..");
  const envPath = resolve(root, ".env.local");

  if (existsSync(envPath)) {
    console.log(".env.local already exists and was left untouched.");
  } else {
    writeFileSync(
      envPath,
      [
        "# Generated by pnpm setup. Development only.",
        "# Point DATABASE_URL at a CockroachDB instance; there is no local fallback.",
        "DATABASE_URL=",
        `AUTH_SECRET=${randomBytes(32).toString("base64url")}`,
        "NEXT_PUBLIC_SITE_URL=http://localhost:3000",
        "NEXT_PUBLIC_SITE_INDEXABLE=false",
        "",
      ].join("\n"),
      "utf8",
    );
    console.log("Created .env.local with a new development signing key.");
  }

  console.log("\nNext:");
  console.log("  1. Set DATABASE_URL in .env.local");
  console.log("  2. pnpm --filter @pv/backend db:migrate");
  console.log("  3. pnpm --filter @pv/backend claim-code --role CEO");
}

main();
