import { randomInt } from "node:crypto";

/**
 * Order references, from a cryptographic source.
 *
 * The prototype built these from `Math.random()` and four digits, into a column
 * marked UNIQUE. Two things are wrong with that, and the second is the one that
 * costs money: `Math.random()` is not a CSPRNG, so references are guessable and
 * therefore enumerable; and at four digits the birthday bound means collisions
 * begin at a few dozen orders — where a collision does not merely look untidy,
 * it throws on insert and fails a real customer's checkout.
 *
 * Ten characters from a 31-character alphabet is about 49.5 bits. At 100,000
 * orders the chance of any collision at all is around 1 in 5.7 million, and the
 * insert is still guarded by the UNIQUE index with a bounded retry, so a
 * collision costs one wasted round trip rather than a failed order.
 */

/**
 * The same alphabet as role codes, and for the same reason: these are read off a
 * screen and typed on a phone, often over the phone. O, I, L, 0 and 1 are gone
 * because they are the pairs people actually confuse.
 */
const ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ";

const REFERENCE_LENGTH = 10;
const GROUP_SIZE = 5;

/** `PV-` prefixed and hyphenated, so it is recognisable in a bank narration. */
export const REFERENCE_PATTERN = /^PV-[2-9A-HJ-NP-Z]{5}-[2-9A-HJ-NP-Z]{5}$/;

/**
 * `randomInt` is rejection-sampled by Node, so the distribution over a 31-letter
 * alphabet is uniform. A `% 31` over raw bytes would not be, and the bias would
 * be small enough to never notice and real enough to reduce the entropy above.
 */
export function generateOrderReference(): string {
  let body = "";
  for (let index = 0; index < REFERENCE_LENGTH; index += 1) {
    body += ALPHABET[randomInt(ALPHABET.length)];
  }
  return `PV-${body.slice(0, GROUP_SIZE)}-${body.slice(GROUP_SIZE)}`;
}

export function isOrderReference(value: string): boolean {
  return REFERENCE_PATTERN.test(value.trim().toUpperCase());
}

/**
 * Accepts what a customer actually types — lower case, spaces instead of
 * hyphens, the prefix left off — and returns the canonical form, or null if it
 * could never be a reference. Being strict here would mean a customer with the
 * right reference and a spacebar cannot find their order.
 */
export function normaliseOrderReference(input: string): string | null {
  const stripped = input.trim().toUpperCase().replace(/[\s-]/g, "");
  const body = stripped.startsWith("PV") ? stripped.slice(2) : stripped;
  if (body.length !== REFERENCE_LENGTH) return null;
  if (![...body].every((character) => ALPHABET.includes(character))) return null;
  return `PV-${body.slice(0, GROUP_SIZE)}-${body.slice(GROUP_SIZE)}`;
}

/**
 * Idempotency keys are generated by the client, but checkout needs one even when
 * the client did not supply it — a form post has no natural place to put a
 * header. This is used by the Server Action adapter, never by the API, where the
 * key arrives in `Idempotency-Key` and a missing one is the caller's error.
 */
export function generateIdempotencyKey(): string {
  let key = "";
  for (let index = 0; index < 32; index += 1) key += ALPHABET[randomInt(ALPHABET.length)];
  return key;
}
