import Image from "next/image";
import { notFound } from "next/navigation";
import { AdminHeader } from "@/components/admin-header";
import { createStaff, updateRequestStatus, updateSettings } from "@/app/admin/(protected)/actions";
import { requirePermission } from "@/lib/auth";
import { all, getCollections, getSetting } from "@/lib/db";
import { permissionsFor, type Permission } from "@/lib/permissions";
import { ROLES } from "@/lib/types";

export const dynamic="force-dynamic";
const sections:Record<string,Permission>={collections:"collections",enquiries:"enquiries","case-requests":"case_requests",customers:"customers",media:"media",content:"content",settings:"settings",staff:"staff",analytics:"analytics",audit:"audit"};
export default async function AdminSectionPage({params}:{params:Promise<{section:string}>}){const {section}=await params;const permission=sections[section];if(!permission)notFound();await requirePermission(permission);if(section==="collections")return <CollectionsAdmin/>;if(section==="enquiries")return <EnquiriesAdmin/>;if(section==="case-requests")return <CaseRequestsAdmin/>;if(section==="customers")return <CustomersAdmin/>;if(section==="media")return <MediaAdmin/>;if(section==="content")return <ContentAdmin/>;if(section==="settings")return <SettingsAdmin/>;if(section==="staff")return <StaffAdmin/>;if(section==="analytics")return <AnalyticsAdmin/>;return <AuditAdmin/>}

function CollectionsAdmin(){const rows=getCollections().map(item=>({...item,count:all<{count:number}>("SELECT COUNT(*) AS count FROM product_collections WHERE collection_id=?",item.id)[0]?.count||0}));return <><AdminHeader eyebrow="Curated catalogue structure" title="Collections" description="Nine connected collection routes used by the public storefront."/><div className="table-wrap"><table className="data-table"><thead><tr><th>Collection</th><th>Description</th><th>Products</th><th>Route</th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td className="font-bold">{item.name}</td><td>{item.description}</td><td>{item.count}</td><td className="font-mono text-xs">/collections/{item.slug}</td></tr>)}</tbody></table></div></>}
function EnquiriesAdmin(){const rows=all<{id:number;reference:string;customer_name:string;contact:string;message:string;status:string;product_name:string|null;created_at:string}>("SELECT e.*,p.name AS product_name FROM enquiries e LEFT JOIN products p ON p.id=e.product_id ORDER BY e.created_at DESC");return <><AdminHeader eyebrow="Prepared customer questions" title="Enquiries"/><div className="table-wrap"><table className="data-table"><thead><tr><th>Reference</th><th>Customer</th><th>Message</th><th>Status</th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td className="font-mono font-bold">{item.reference}</td><td><strong>{item.customer_name}</strong><p className="text-xs text-zinc-500">{item.contact}</p></td><td><p className="max-w-md">{item.message}</p><p className="mt-1 text-xs text-zinc-500">{item.product_name}</p></td><td><StatusForm section="enquiries" id={item.id} current={item.status} states={["new","responded","closed"]}/></td></tr>)}</tbody></table></div></>}
function CaseRequestsAdmin(){const rows=all<{id:number;reference:string;customer_name:string;contact:string;brand:string;model:string;preferences:string;status:string}>("SELECT * FROM case_requests ORDER BY created_at DESC");return <><AdminHeader eyebrow="Unmet model and style demand" title="Case requests"/><div className="table-wrap"><table className="data-table"><thead><tr><th>Reference</th><th>Customer</th><th>Exact device</th><th>Preferences</th><th>Status</th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td className="font-mono font-bold">{item.reference}</td><td><strong>{item.customer_name}</strong><p className="text-xs text-zinc-500">{item.contact}</p></td><td>{item.brand} {item.model}</td><td>{item.preferences}</td><td><StatusForm section="case_requests" id={item.id} current={item.status} states={["new","reviewing","sourced","closed"]}/></td></tr>)}</tbody></table></div></>}
function StatusForm({section,id,current,states}:{section:string;id:number;current:string;states:string[]}){return <form action={updateRequestStatus} className="flex gap-2"><input type="hidden" name="section" value={section}/><input type="hidden" name="id" value={id}/><select className="field min-h-9 w-32 py-1 text-xs" name="status" defaultValue={current}>{states.map(state=><option key={state}>{state}</option>)}</select><button className="button-ghost min-h-9 px-2 py-1 text-xs">Save</button></form>}
function CustomersAdmin(){const rows=all<{customer_name:string;contact:string;reservations:number;latest:string}>("SELECT customer_name,contact,COUNT(*) AS reservations,MAX(created_at) AS latest FROM reservations GROUP BY customer_name,contact ORDER BY latest DESC");return <><AdminHeader eyebrow="Prototype request contacts" title="Customers" description="Aggregated only from demonstration reservation records; there are no public customer accounts."/><div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Contact</th><th>Reservations</th><th>Latest activity</th></tr></thead><tbody>{rows.map(item=><tr key={`${item.customer_name}-${item.contact}`}><td className="font-bold">{item.customer_name}</td><td>{item.contact}</td><td>{item.reservations}</td><td>{item.latest}</td></tr>)}</tbody></table></div></>}
const media=["case-blush.png","case-rugged.png","case-red-clear.png","case-sage.png","case-smoke.png","pouch-villa-hero.png","phone-cases-display.jpg"];
function MediaAdmin(){return <><AdminHeader eyebrow="Approved prototype assets" title="Media library" description="Product forms can select these assets or upload PNG, JPG or WebP files up to 5 MB."/><div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{media.map(file=><div className="card-surface overflow-hidden" key={file}><div className="relative aspect-square bg-[#f6f3f1]"><Image src={`/images/${file}`} alt={file} fill sizes="300px" className="object-cover"/></div><p className="truncate p-3 text-xs font-bold">{file}</p></div>)}</div></>}
function ContentAdmin(){return <><AdminHeader eyebrow="Homepage copy control" title="Homepage & content" description="Prototype content management uses the same settings records as the storefront."/><form action={updateSettings} className="card-surface grid max-w-3xl gap-5 p-6"><input type="hidden" name="store_address" value={getSetting("store_address")}/><input type="hidden" name="opening_hours" value={getSetting("opening_hours")}/><input type="hidden" name="whatsapp_number" value={getSetting("whatsapp_number")}/><label><span className="label">Homepage announcement</span><textarea className="field min-h-28" name="homepage_announcement" defaultValue={getSetting("homepage_announcement")}/></label><button className="button-primary justify-self-start">Save homepage content</button></form></>}
function SettingsAdmin(){return <><AdminHeader eyebrow="Client confirmation controls" title="Business settings" description="Blank fields are shown publicly as awaiting confirmation. Add only details approved by Pouch Hub."/><form action={updateSettings} className="card-surface grid max-w-3xl gap-5 p-6"><label><span className="label">Store address</span><input className="field" name="store_address" defaultValue={getSetting("store_address")}/></label><label><span className="label">Opening hours</span><textarea className="field min-h-24" name="opening_hours" defaultValue={getSetting("opening_hours")}/></label><label><span className="label">Official WhatsApp number</span><input className="field" name="whatsapp_number" defaultValue={getSetting("whatsapp_number")} placeholder="International digits only after approval"/></label><label><span className="label">Homepage announcement</span><textarea className="field min-h-24" name="homepage_announcement" defaultValue={getSetting("homepage_announcement")}/></label><button className="button-primary justify-self-start">Save confirmed settings</button></form></>}
function StaffAdmin(){const staff=all<{id:number;name:string;email:string;role:string;status:string;last_login_at:string|null}>("SELECT id,name,email,role,status,last_login_at FROM staff ORDER BY created_at");return <><AdminHeader eyebrow="Identity and access" title="Staff accounts, roles & permissions" description="Owner-only account creation. Every privileged action independently verifies the server session and required permission."/><div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Role</th><th>Status</th><th>Last sign-in</th></tr></thead><tbody>{staff.map(item=><tr key={item.id}><td><strong>{item.name}</strong><p className="text-xs text-zinc-500">{item.email}</p></td><td><span className="status-pill bg-red-50 text-[#b9020c]">{item.role}</span></td><td>{item.status}</td><td>{item.last_login_at||"Never"}</td></tr>)}</tbody></table></div><form action={createStaff} className="card-surface grid gap-4 p-5"><h2 className="text-lg font-bold">Create demonstration staff account</h2><label><span className="label">Name</span><input className="field" name="name" required/></label><label><span className="label">Email</span><input className="field" type="email" name="email" required/></label><label><span className="label">Temporary password</span><input className="field" type="password" name="password" minLength={12} required/></label><label><span className="label">Role</span><select className="field" name="role">{ROLES.map(role=><option key={role}>{role}</option>)}</select></label><button className="button-primary">Create account</button></form></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{ROLES.map(role=><div className="card-surface p-5" key={role}><h3 className="font-bold capitalize">{role}</h3><p className="mt-3 text-xs leading-5 text-zinc-500">{permissionsFor(role).join(" · ")}</p></div>)}</div></>}
function AnalyticsAdmin(){const events=all<{event_type:string,value:string,count:number}>("SELECT event_type,value,COUNT(*) AS count FROM analytics_events GROUP BY event_type,value ORDER BY event_type,count DESC");const views=all<{name:string;views:number}>("SELECT name,views FROM products ORDER BY views DESC LIMIT 10");return <><AdminHeader eyebrow="Basic prototype intelligence" title="Analytics" description="Seeded demonstration activity plus local page views. No tracking of real people."/><div className="grid gap-6 xl:grid-cols-2"><div className="card-surface p-5"><h2 className="text-lg font-bold">Event summary</h2><div className="mt-4 divide-y divide-[#e8e3df]">{events.map(item=><div key={`${item.event_type}-${item.value}`} className="flex justify-between gap-4 py-3 text-sm"><span><strong className="block">{item.value}</strong><small className="text-zinc-500">{item.event_type.replaceAll("_"," ")}</small></span><strong>{item.count}</strong></div>)}</div></div><div className="card-surface p-5"><h2 className="text-lg font-bold">Most viewed products</h2><div className="mt-4 divide-y divide-[#e8e3df]">{views.map(item=><div key={item.name} className="flex justify-between py-3 text-sm"><span>{item.name}</span><strong>{item.views}</strong></div>)}</div></div></div></>}
function AuditAdmin(){const rows=all<{id:number;staff_name:string|null;action:string;entity_type:string;entity_id:string;details:string;created_at:string}>("SELECT a.*,s.name AS staff_name FROM audit_logs a LEFT JOIN staff s ON s.id=a.staff_id ORDER BY a.created_at DESC LIMIT 100");return <><AdminHeader eyebrow="Accountability trail" title="Audit history" description="Records privileged staff mutations with actor, entity, details and timestamp."/><div className="table-wrap"><table className="data-table"><thead><tr><th>Time</th><th>Staff</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td className="text-xs">{item.created_at}</td><td>{item.staff_name||"Deleted staff"}</td><td className="font-bold">{item.action.replaceAll("_"," ")}</td><td>{item.entity_type} #{item.entity_id}</td><td>{item.details}</td></tr>)}</tbody></table></div></>}
